# Generated by Django 4.1 on 2024-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom1', models.CharField(max_length=100)),
                ('start1', models.IntegerField()),
                ('end1', models.IntegerField()),
                ('chrom2', models.CharField(max_length=100)),
                ('start2', models.IntegerField()),
                ('end2', models.IntegerField()),
                ('petCounts', models.IntegerField()),
                ('GenomicAnno1', models.TextField()),
                ('GenomicAnno2', models.TextField()),
                ('ENCODE_ATAC1', models.TextField()),
                ('ENCODE_ATAC2', models.TextField()),
                ('TCGA_ATAC1', models.TextField()),
                ('TCGA_ATAC2', models.TextField()),
            ],
            options={
                'db_table': 'AnnotationResult',
            },
        ),
    ]
