# Generated by Django 4.1 on 2023-12-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChromLoopsCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom1', models.CharField(max_length=5)),
                ('start1', models.IntegerField()),
                ('end1', models.IntegerField()),
                ('chrom2', models.CharField(max_length=5)),
                ('start2', models.IntegerField()),
                ('end2', models.IntegerField()),
                ('counts', models.IntegerField()),
                ('anchor1_in_cancer', models.TextField()),
                ('anchor2_in_cancer', models.TextField()),
                ('anchor1_genes', models.TextField()),
                ('anchor2_genes', models.TextField()),
                ('file_id', models.CharField(max_length=50)),
                ('body_site', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ChromLoopsCancer',
            },
        ),
        migrations.CreateModel(
            name='NonCodingElementSNV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom_snv', models.CharField(max_length=5)),
                ('start_snv', models.IntegerField()),
                ('end_snv', models.IntegerField()),
                ('info', models.TextField()),
                ('cancer_type_snv', models.CharField(max_length=30)),
                ('chrom_cre', models.CharField(max_length=5)),
                ('start_cre', models.IntegerField()),
                ('end_cre', models.IntegerField()),
                ('cre_id', models.CharField(max_length=20)),
                ('cancer_type_cre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'NonCodingElementSNV',
            },
        ),
        migrations.CreateModel(
            name='NonCodingElementSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom_sv', models.CharField(max_length=5)),
                ('start_sv', models.IntegerField()),
                ('end_sv', models.IntegerField()),
                ('info', models.TextField()),
                ('cancer_type_sv', models.CharField(max_length=30)),
                ('chrom_cre', models.CharField(max_length=5)),
                ('start_cre', models.IntegerField()),
                ('end_cre', models.IntegerField()),
                ('cre_id', models.CharField(max_length=20)),
                ('cancer_type_cre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'NonCodingElementSV',
            },
        ),
    ]
