/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTrack: typeof import('./src/components/Browser/AddTrack.vue')['default']
    AnchorStat: typeof import('./src/components/Annotation/AnchorStat.vue')['default']
    Annotation: typeof import('./src/components/Annotation/index.vue')['default']
    AnnotationDetail: typeof import('./src/components/Annotation/AnnotationDetail.vue')['default']
    Browser: typeof import('./src/components/Browser/index.vue')['default']
    CancerAtacStat: typeof import('./src/components/Annotation/CancerAtacStat.vue')['default']
    CancerBodyMap: typeof import('./src/components/CancerCRE/CancerBodyMap.vue')['default']
    CancerCRE: typeof import('./src/components/CancerCRE/index.vue')['default']
    CancerCREDetail: typeof import('./src/components/CancerCRE/CancerCREDetail.vue')['default']
    CellType: typeof import('./src/components/CellType/CellType.vue')['default']
    CellTypeSummaryChart: typeof import('./src/components/LandingView/CellTypeSummaryChart.vue')['default']
    ChromatinInteractionsFilter: typeof import('./src/components/search/ChromatinInteractionsFilter.vue')['default']
    ChromatinInteractionSummaryChart: typeof import('./src/components/LandingView/ChromatinInteractionSummaryChart.vue')['default']
    CloudDatasetChart: typeof import('./src/components/LandingView/CloudDatasetChart.vue')['default']
    CollapseItem: typeof import('./src/components/search/CollapseItem.vue')['default']
    copy: typeof import('./src/components/search/search copy.vue')['default']
    DataList: typeof import('./src/components/DataList/DataList.vue')['default']
    DevTimeLine: typeof import('./src/components/LandingView/DevTimeLine.vue')['default']
    Documentation: typeof import('./src/components/Documentation/index.vue')['default']
    Download: typeof import('./src/components/Download/index.vue')['default']
    ExTrackForm: typeof import('./src/components/Browser/ExTrackForm.vue')['default']
    FacebookIcon: typeof import('./src/components/icons/FacebookIcon.vue')['default']
    FrontPageCarousel: typeof import('./src/components/LandingView/FrontPageCarousel.vue')['default']
    Index2: typeof import('./src/components/Browser/index2.vue')['default']
    InstagramIcon: typeof import('./src/components/icons/InstagramIcon.vue')['default']
    InteractionStat: typeof import('./src/components/Annotation/InteractionStat.vue')['default']
    Introduction: typeof import('./src/components/LandingView/Introduction.vue')['default']
    LandingView: typeof import('./src/components/LandingView/LandingView.vue')['default']
    LoadedTrack: typeof import('./src/components/Browser/LoadedTrack.vue')['default']
    LogoIcon: typeof import('./src/components/icons/LogoIcon.vue')['default']
    NavBar: typeof import('./src/components/search/NavBar.vue')['default']
    NoncodingMutationChart: typeof import('./src/components/LandingView/NoncodingMutationChart.vue')['default']
    NormalAtacStat: typeof import('./src/components/Annotation/NormalAtacStat.vue')['default']
    PinterestIcon: typeof import('./src/components/icons/PinterestIcon.vue')['default']
    ResetFiltersButton: typeof import('./src/components/search/ResetFiltersButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/search.vue')['default']
    'Search copy': typeof import('./src/components/search/search copy.vue')['default']
    SearchList: typeof import('./src/components/search/SearchList.vue')['default']
    ShowFilterTrigger: typeof import('./src/components/search/ShowFilterTrigger.vue')['default']
    TrackList: typeof import('./src/components/search/TrackList.vue')['default']
    TwitterIcon: typeof import('./src/components/icons/TwitterIcon.vue')['default']
    Uploads: typeof import('./src/components/Annotation/Uploads.vue')['default']
    UploadTrack: typeof import('./src/components/Browser/UploadTrack.vue')['default']
    YoutubeIcon: typeof import('./src/components/icons/YoutubeIcon.vue')['default']
  }
}
