# Generated by Django 4.1 on 2023-12-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('name', models.CharField(choices=[('ChIA-PET', 'ChIA-PET'), ('HiChIP', 'HiChIP'), ('ATAC-seq', 'ATAC-seq'), ('RNA-seq', 'RNA-seq'), ('ChIP-seq', 'ChIP-seq')], max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'Assay',
            },
        ),
        migrations.CreateModel(
            name='CellTypeSummary',
            fields=[
                ('cell_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cell_type', models.CharField(choices=[('Cell line', 'Cell line'), ('Primary cell', 'Primary cell')], max_length=20)),
                ('disease_status', models.CharField(choices=[('Cancer', 'Cancer'), ('Non-Cancer', 'Non-Cancer')], max_length=20)),
                ('body_site', models.CharField(choices=[('Aortic valves', 'Aortic valves'), ('Artery', 'Artery'), ('Ascites', 'Ascites'), ('B lymphocyte', 'B lymphocyte'), ('Blood', 'Blood'), ('Bone', 'Bone'), ('Bone marrow', 'Bone marrow'), ('Brain', 'Brain'), ('Breast', 'Breast'), ('Cervix', 'Cervix'), ('Colon', 'Colon'), ('Embryonic', 'Embryonic'), ('Esophagus', 'Esophagus'), ('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Large intestine', 'Large intestine'), ('Liver', 'Liver'), ('Lung', 'Lung'), ('Lymph', 'Lymph'), ('Muscle', 'Muscle'), ('Myeloid', 'Myeloid'), ('Ovary', 'Ovary'), ('Pancreas', 'Pancreas'), ('Prostate', 'Prostate'), ('Skin', 'Skin'), ('Soft Tissue', 'Soft Tissue'), ('Stomach', 'Stomach'), ('Umbilical cord', 'Umbilical cord'), ('Uterus', 'Uterus')], max_length=20)),
                ('factor', models.CharField(choices=[('RNAPII', 'RNAPII'), ('H3K27ac', 'H3K27ac')], max_length=20)),
                ('assays', models.ManyToManyField(to='chromatinLoops.assay')),
            ],
            options={
                'db_table': 'CellTypeSummary',
            },
        ),
        migrations.CreateModel(
            name='ChromLoops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom1', models.CharField(max_length=255)),
                ('start1', models.IntegerField()),
                ('end1', models.IntegerField()),
                ('chrom2', models.CharField(max_length=255)),
                ('start2', models.IntegerField()),
                ('end2', models.IntegerField()),
                ('counts', models.IntegerField(default=2)),
                ('anchor1', models.TextField()),
                ('anchor2', models.TextField()),
                ('file_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ChromLoops',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=255)),
                ('assay', models.CharField(choices=[('ChIA-PET', 'ChIA-PET'), ('HiChIP', 'HiChIP'), ('ChIP-seq', 'ChIP-seq'), ('ATAC-seq', 'ATAC-seq'), ('RNA-seq', 'RNA-seq')], max_length=20)),
                ('format', models.CharField(choices=[('bedpe', 'bedpe'), ('bed', 'bed'), ('hic', 'hic'), ('bigwig', 'bigwig'), ('txt', 'txt')], max_length=20)),
                ('cell_type_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chromatinLoops.celltypesummary')),
            ],
            options={
                'db_table': 'File',
            },
        ),
    ]
