# Generated by Django 4.1 on 2023-12-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromatinLoops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromloops',
            name='file_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
